[theme]
primaryColor = "#0F1C3F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = false
enableCORS = false
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
